---
version: '3.8'

networks:
  internal_network:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./apps/nginx/default-ssl.conf:/etc/nginx/conf.d/default.conf:ro 
      - ./.cert/localhost.crt:/etc/cert/localhost.crt
      - ./.cert/localhost.key:/etc/cert/localhost.key
    networks:
      - internal_network
    ports:
      - "80:80"
      - "443:443"

  frontend: 
    image: node:23-bookworm
    container_name: frontend
    hostname: frontend
    working_dir: /app 
    volumes:
      - ./apps/frontend:/app
    networks:
      - internal_network
    command: /bin/bash -c 'npm install && npm run dev'

  backend: 
    image: node:23-bookworm
    container_name: backend
    hostname: backend
    working_dir: /app 
    volumes:
      - ./apps/backend:/app
    networks:
      - internal_network
    command: /bin/bash -c 'npm install && npm run start:dev'

  fastapi: 
    image: python:3
    container_name: fastapi
    hostname: fastapi
    working_dir: /app 
    volumes:
      - ./apps/converter:/app
    networks:
      - internal_network
    command: /bin/bash -c 'python -m venv /etc/venv/ && source /etc/venv/bin/activate && pip install "fastapi[standard]" && pip install "uvicorn[standard]" && pip install asyncio && uvicorn main:app --host 0.0.0.0 --port 8000 --reload'

  converter: 
    image: nikolaik/python-nodejs:python3.9-nodejs23
    container_name: converter
    hostname: converter
    working_dir: /app 
    volumes:
      - ./apps/converter:/app
    networks:
      - internal_network
    command: /bin/bash -c 'npm install -g nodemon && python -m venv /etc/venv/ && source /etc/venv/bin/activate && pip install python-ffmpeg && pip install asyncio && nodemon --exec python3 -u worker.py'
